-- CreateTable
CREATE TABLE "login" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "admin" BOOLEAN NOT NULL DEFAULT false,
    "role" TEXT NOT NULL,
    "unity" TEXT[],

    CONSTRAINT "login_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "person" (
    "name" TEXT NOT NULL,
    "owner" TEXT NOT NULL,
    "aluno" TEXT NOT NULL,
    "unidade" TEXT NOT NULL,
    "contrato" TEXT NOT NULL,
    "background" TEXT NOT NULL,
    "classe" TEXT NOT NULL,
    "subclasse" TEXT NOT NULL,
    "tmStatus" TEXT NOT NULL,
    "tmVencimento" TEXT NOT NULL,
    "tmValor" TEXT NOT NULL,
    "ppVencimento" TEXT NOT NULL,
    "ppStatus" TEXT NOT NULL,
    "mdValor" TEXT NOT NULL,
    "mdStatus" TEXT NOT NULL,
    "acFormato" TEXT NOT NULL,
    "tipoMatricula" TEXT NOT NULL,
    "tipoComissao" TEXT NOT NULL,
    "comissaoValor" TEXT NOT NULL,
    "aprovacaoADM" TEXT NOT NULL,
    "responsavelADM" TEXT NOT NULL,
    "aprovacaoDirecao" TEXT NOT NULL,
    "diretorResponsavel" TEXT NOT NULL,
    "paDATA" TEXT NOT NULL,
    "inicioContrato" TEXT NOT NULL,
    "fimContrato" TEXT NOT NULL,
    "tel" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "Valor" DOUBLE PRECISION NOT NULL,
    "id" INTEGER NOT NULL,
    "paStatus" TEXT NOT NULL,
    "situMatric" TEXT NOT NULL,
    "acStatus" TEXT NOT NULL,
    "alunoNascimento" TEXT NOT NULL,
    "cargaHoraria" TEXT NOT NULL,
    "contratoStatus" TEXT NOT NULL,
    "dataComissionamento" TEXT NOT NULL,
    "dataMatricula" TEXT NOT NULL,
    "dataValidacao" TEXT NOT NULL,
    "formatoAula" TEXT NOT NULL,
    "horarioFim" TEXT NOT NULL,
    "horarioInicio" TEXT NOT NULL,
    "idadeAluno" TEXT NOT NULL,
    "materialDidatico" TEXT[],
    "mdData" TEXT NOT NULL,
    "mdDesconto" TEXT NOT NULL,
    "mdFormaPg" TEXT NOT NULL,
    "mdParcelas" TEXT NOT NULL,
    "mdVencimento" TEXT NOT NULL,
    "nivelamento" TEXT NOT NULL,
    "observacao" TEXT NOT NULL,
    "ppData" TEXT NOT NULL,
    "ppDesconto" TEXT NOT NULL,
    "ppFormaPg" TEXT NOT NULL,
    "ppParcelas" TEXT NOT NULL,
    "ppValor" TEXT NOT NULL,
    "tempoContrato" TEXT NOT NULL,
    "tipoModalidade" TEXT NOT NULL,
    "tmData" TEXT NOT NULL,
    "tmDesconto" TEXT NOT NULL,
    "tmFormaPg" TEXT NOT NULL,
    "tmParcelas" TEXT NOT NULL,
    "dataAC" JSONB[],
    "diaAula" TEXT[],
    "comissaoStatus" TEXT NOT NULL,
    "professor" TEXT[],

    CONSTRAINT "person_pkey" PRIMARY KEY ("contrato")
);

-- CreateIndex
CREATE UNIQUE INDEX "login_email_key" ON "login"("email");
